import type { AiPdfLineItemFieldOption, AiPdfSyncTableInput, AiPdfSyncPayload } from './types'


export const LINE_ITEM_FIELD_OPTIONS = [
    { key: 'adjusted_price', label: 'Adjusted Price' },
    { key: 'adjusted_quantity', label: 'Adjusted Quantity' },
    { key: 'amount', label: 'Amount' },
    { key: 'attemptNumber', label: 'Attempt Number' },
    { key: 'availability', label: 'Availability' },
    { key: 'bundle_cost', label: 'Bundle Cost' },
    { key: 'bundle_ext_price', label: 'Bundle Ext Price' },
    { key: 'bundle_gp', label: 'Bundle GP' },
    { key: 'bundle_gp_percentage', label: 'Bundle GP Percentage' },
    { key: 'bundle_msrp', label: 'Bundle MSRP' },
    { key: 'bundle_name', label: 'Bundle Name' },
    { key: 'bundle_rebate', label: 'Bundle Rebate' },
    { key: 'bundle_rebate_amount', label: 'Bundle Rebate Amount' },
    { key: 'bundle_unit_price', label: 'Bundle Unit Price' },
    { key: 'category', label: 'Category' },
    { key: 'changeFlag', label: 'Change Flag' },
    { key: 'changeSource', label: 'Change Source' },
    { key: 'clin', label: 'CLIN' },
    { key: 'contract_fee_amount', label: 'Contract Fee Amount' },
    { key: 'contract_fee_percentage', label: 'Contract Fee Percentage' },
    { key: 'country_of_origin', label: 'Country of Origin' },
    { key: 'currency', label: 'Currency' },
    { key: 'department', label: 'Department' },
    { key: 'description', label: 'Description' },
    { key: 'Discount_Class__c', label: 'Discount Class' },
    { key: 'discount_percentage', label: 'Discount Percentage' },
    { key: 'Discount_Subclass__c', label: 'Discount Subclass' },
    { key: 'display_mpn', label: 'Display MPN' },
    { key: 'distributor_product_code', label: 'Distributor Product Code' },
    { key: 'email', label: 'Email' },
    { key: 'employeeId', label: 'Employee ID' },
    { key: 'employeeName', label: 'Employee Name' },
    { key: 'end_date', label: 'End Date' },
    { key: 'energy_star_flag', label: 'Energy Star Flag' },
    { key: 'eol_date', label: 'EOL Date' },
    { key: 'epeat_flag', label: 'EPEAT Flag' },
    { key: 'equivalent_clin', label: 'Equivalent CLIN' },
    { key: 'esi_price', label: 'ESI Price' },
    { key: 'excel_bundle_name', label: 'Excel Bundle Name' },
    { key: 'extended_list', label: 'Extended List' },
    { key: 'file_name', label: 'File Name' },
    { key: 'gross_profit', label: 'Gross Profit' },
    { key: 'gross_profit_percentage', label: 'Gross Profit Percentage' },
    { key: 'gsa_price', label: 'GSA Price' },
    { key: 'item_category_code', label: 'Item Category Code' },
    { key: 'itemCode', label: 'Item Code' },
    { key: 'lead_time', label: 'Lead Time' },
    { key: 'line_amount', label: 'Line Amount' },
    { key: 'lineNumber', label: 'Line Number' },
    { key: 'list_price', label: 'List Price' },
    { key: 'location', label: 'Location' },
    { key: 'ma_flag', label: 'MA Flag' },
    { key: 'manufacturer_product_code', label: 'Manufacturer Product Code' },
    { key: 'model_id', label: 'Model ID' },
    { key: 'months', label: 'Months' },
    { key: 'mpn', label: 'MPN' },
    { key: 'msrp', label: 'MSRP' },
    { key: 'ndr_cost', label: 'NDR Cost' },
    { key: 'notes', label: 'Notes' },
    { key: 'objectId', label: 'Object ID' },
    { key: 'occurredAt', label: 'Occurred At' },
    { key: 'oem', label: 'OEM' },
    { key: 'oem_name', label: 'OEM Name' },
    { key: 'organization', label: 'Organization' },
    { key: 'partner_fee_amount', label: 'Partner Fee Amount' },
    { key: 'partner_fee_percentage', label: 'Partner Fee Percentage' },
    { key: 'pdf_url', label: 'PDF URL' },
    { key: 'phone', label: 'Phone' },
    { key: 'portalId', label: 'Portal ID' },
    { key: 'pricing_method', label: 'Pricing Method' },
    { key: 'product_name', label: 'Product Name' },
    { key: 'quantity', label: 'Quantity' },
    { key: 'referenceNo', label: 'Reference No' },
    { key: 'salary', label: 'Salary' },
    { key: 'serial_', label: 'Serial' },
    { key: 'serial_number', label: 'Serial Number' },
    { key: 'service_duration', label: 'Service Duration' },
    { key: 'sku', label: 'SKU' },
    { key: 'ss_part', label: 'SS Part' },
    { key: 'start_date', label: 'Start Date' },
    { key: 'status', label: 'Status' },
    { key: 'sub_total', label: 'Sub Total' },
    { key: 'subscription_term', label: 'Subscription Term' },
    { key: 'subscriptionId', label: 'Subscription ID' },
    { key: 'subscriptionType', label: 'Subscription Type' },
    { key: 'taa_flag', label: 'TAA Flag' },
    { key: 'td_number', label: 'TD Number' },
    { key: 'term_months', label: 'Term Months' },
    { key: 'term_unit_calc', label: 'Term Unit Calc' },
    { key: 'term_years', label: 'Term Years' },
    { key: 'total_cost', label: 'Total Cost' },
    { key: 'total_cost_to_use', label: 'Total Cost to Use' },
    { key: 'unit_price', label: 'Unit Price (Extended)' },
    { key: 'unitPrice', label: 'Unit Price' },
    { key: 'unspsc', label: 'UNSPSC' },
    { key: 'vendor_disti', label: 'Vendor Disti' },
    { key: 'vendor_disti_name', label: 'Vendor Disti Name' },
    { key: 'vendor_line_number', label: 'Vendor Line Number' },
    { key: 'vendor_product_code', label: 'Vendor Product Code' },
    { key: 'vendor_quote_line_item', label: 'Vendor Quote Line Item' },
    { key: 'vendor_quote_number', label: 'Vendor Quote Number' },
] as const satisfies AiPdfLineItemFieldOption[]

export const LINE_ITEM_FIELD_KEYS = new Set<string>(
    LINE_ITEM_FIELD_OPTIONS.map((f) => f.key)
)

// Run this before dispatching syncAiPdfUpload — backend trusts the shape now
export const normalizeSyncPayload = (tables: AiPdfSyncTableInput[]): AiPdfSyncPayload => ({
    tables: tables.map((table, _ti) => ({
        ...table,
        columns: Array.isArray(table.columns) ? table.columns : [],
        rows: Array.isArray(table.rows)
            ? table.rows.map((row, i) => ({
                id: row.id,
                rowData: row.rowData && typeof row.rowData === 'object' ? row.rowData : {},
                rowIndex: typeof row.rowIndex === 'number' ? row.rowIndex : i,
            }))
            : [],
        lineItemMapping: Object.fromEntries(
            Object.entries(table.lineItemMapping ?? {}).filter(
                ([, v]) => LINE_ITEM_FIELD_KEYS.has(v)
            )
        ),
    })),
})